# Generated by Django 5.2.14 on 2026-05-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_vote_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='total_students',
            field=models.IntegerField(default=0, verbose_name='Total de Estudiantes'),
        ),
    ]
