# Generated by Django 5.2.13 on 2026-05-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_section_total_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinKinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código PIN')),
                ('used', models.BooleanField(default=False, verbose_name='Usado')),
            ],
        ),
        migrations.CreateModel(
            name='VotoKinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=20, verbose_name='PIN usado')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.candidate', verbose_name='Candidato')),
            ],
        ),
    ]
